# Generated by Django 5.1.15 on 2026-02-09 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_batch'),
        ('subjects', '0002_alter_subject_options_subject_syllabus_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='Auto-calculated: 3 years after admission', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Studying (Active)'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped Out')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(choices=[('AA', 'AA (10)'), ('AB', 'AB (9)'), ('BB', 'BB (8)'), ('BC', 'BC (7)'), ('CC', 'CC (6)'), ('CD', 'CD (5)'), ('DD', 'DD (4)'), ('FF', 'Fail (0)')], help_text='Select standard grade', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'exam_name')},
        ),
    ]
