# Generated by Django 5.1.15 on 2026-02-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_initials'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester', 'code']},
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_url',
            field=models.URLField(blank=True, help_text='Link to GTU syllabus PDF', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='faculty.faculty'),
        ),
    ]
