# Generated by Django 5.1.15 on 2026-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='area_of_interest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='courses_taught',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institute_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='portfolio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=100),
        ),
    ]
