# Generated by Django 5.1.15 on 2026-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_area_of_interest_faculty_courses_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
    ]
