# Generated by Django 5.1.15 on 2026-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='initials',
            field=models.CharField(blank=True, help_text='e.g. KKP, BGP', max_length=5),
        ),
    ]
