# Generated by Django 5.1.15 on 2026-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MID', 'Mid-Semester'), ('REM', 'Remedial'), ('PRAC', 'Practical')], default='MID', max_length=10),
        ),
    ]
