# Generated by Django 5.1.15 on 2026-02-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_created_at_exam_is_published_exam_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('exam_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='exams.examsubject')),
            ],
        ),
    ]
