# Generated by Django 5.1.15 on 2026-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='tag',
            field=models.CharField(blank=True, choices=[('Question', 'Question'), ('Doubt', 'Doubt'), ('Resource', 'Resource'), ('Announcement', 'Announcement')], default='Question', max_length=20),
        ),
    ]
