# Generated by Django 5.1.15 on 2026-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENT', 'Students Only'), ('FACULTY', 'Faculty Only')], default='ALL', max_length=10)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Urgent / High')], default='NORMAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
